#!/bin/bash
#
# Author: Mike Purvis <mpurvis@clearpathrobotics.com>
#         Copyright (c) 2013, Clearpath Robotics, Inc.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#    * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#    * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#    * Neither the name of Clearpath Robotics, Inc. nor the
#       names of its contributors may be used to endorse or promote products
#       derived from this software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL CLEARPATH ROBOTICS, INC. BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
# 
# Please send comments, questions, or patches to code@clearpathrobotics.com 
ROBOT=$ROBOT
DISTRO=indigo
WITHARM=$WITHARM

function log() {
  logger -s -p user.$1 ${@:2}
}

if ($WITHARM); then
  sh /home/squirrel/squirrel_recommender/setup_robotino/upstart/arm-start &
  PID=$!
  echo "arm started with PID" 
  echo $PID
  log info "robot.launch: Started roslaunch as background process, PID $PID"
  echo "$PID" > /tmp/start_arm.pid
  wait
fi
echo "finish"

source /etc/ros/$DISTRO/robotino.d/setup/setup.sh

JOB_FOLDER=/etc/ros/$DISTRO/robotino.d/launch/robot

log info "Provided the following robot:=$ROBOT"

export ROS_IP=`rosrun robot_upstart getifip eth0`
export ROS_MASTER_URI=http://localhost:11311
if [ "$ROS_IP" = "" ]; then
  log err "robot.launch: No IP address on eth0, cannot roslaunch."
  exit 1
fi
log info "robot.launch: Launching on interface eth0, ROS_IP=$ROS_IP, ROS_MASTER_URI=$ROS_MASTER_URI"


# Assemble amalgamated launchfile.
LAUNCH_FILENAME=/tmp/robot.launch.launch
rosrun robot_upstart mklaunch $JOB_FOLDER robot:=$ROBOT > $LAUNCH_FILENAME
if [[ "$?" != "0" ]]; then
  log err "robot.launch: Unable to generate amalgamated launchfile."
  exit 1
fi
log info "robot.launch: Generated launchfile: $LAUNCH_FILENAME"

# Warn and exit if setuidgid is missing from the system.
which setuidgid > /dev/null
if [ "$?" != "0" ]; then
  log err "robot.launch: Can't launch as unprivileged user without setuidgid. Please install daemontools package."
  exit 1
fi

# Punch it.
export ROS_HOME=$(echo ~squirrel)/.ros
export ROS_LOG_DIR=/tmp
setuidgid squirrel roslaunch $LAUNCH_FILENAME robot:=$ROBOT &
PID=$!

log info "robot.launch: Started roslaunch as background process, PID $PID"
echo "$PID" > /tmp/robot.launch.pid

wait "$PID"
