#!/bin/bash

if [ "$HOSTNAME" != "scrat" ]; then 
	echo "FATAL: CAN ONLY BE EXECUTED ON scrat PC"
	exit
fi

echo "Executing adduser"
sudo /usr/sbin/adduser $1 --u /u/$1
sudo adduser $1 dialout 
sudo adduser $1 cdrom 
sudo adduser $1 floppy 
sudo adduser $1 audio
sudo adduser $1 video
sudo adduser $1 plugdev
sudo adduser $1 users 

echo "Syncing passwd file to other pcs"
sudo rsync -e ssh -avz /etc/passwd /etc/shadow /etc/group root@robotino:/etc/

if [ "$1" != "" ]; then
	echo "setup bash environment"
	sudo cp /u/squirrel/squirrel_recommender/setup_robotino/user.bashrc  /u/$1/.bashrc
	sudo sed -i "s/myrobot/$ROBOT/g" /u/$1/.bashrc
	sudo sed -i "s/mydistro/$ROS_DISTRO/g" /u/$1/.bashrc


	if [ ! -d /u/$1/.ssh ]; then
		echo "create new ssh key"
		sudo -u $1 ssh-keygen
	fi

	echo "copying ssh-keys to other pcs, please enter password of new user"
	sudo -u $1 cat /u/$1/.ssh/id_rsa.pub | ssh $1@robotino "cat >> /u/$1/.ssh/authorized_keys"
	sudo -u $1 ssh $1@robotino 'exit'
	echo "copying ssh-keys to other pcs, please enter password of new user"
	sudo -u $1 cat /u/$1/.ssh/id_rsa.pub | ssh pi@raspberrypi "cat >> /u/$1/.ssh/authorized_keys"
	sudo -u $1 ssh pi@raspberrypi 'exit'

	sudo su -c "rosdep update" $1
	sudo su -c "mkdir -p ~/catkin_ws" $1
    
	echo "done adding user"
else
	echo "No username provided"
fi

