#!/bin/bash

if [ "$1" != "" ]; then
    echo "Executing adduser"
    sudo /usr/sbin/adduser $1
    sudo adduser $1 dialout 
    sudo adduser $1 cdrom 
    sudo adduser $1 floppy 
    sudo adduser $1 audio
    sudo adduser $1 video
    sudo adduser $1 plugdev
    sudo adduser $1 users 

	echo "setup bash environment"
	sudo cp /home/squirrel/squirrel_recommender/setup_robotino/user.bashrc  /home/$1/.bashrc
	sudo sed -i "s/myrobot/$ROBOT/g" /home/$1/.bashrc
	sudo sed -i "s/mydistro/$ROS_DISTRO/g" /home/$1/.bashrc


	if [ ! -d /home/$1/.ssh ]; then
		echo "create new ssh key"
		sudo -u $1 ssh-keygen
	fi

	echo "copying ssh-keys to other pcs, please enter password of new user"
	sudo -u $1 cat /home/$1/.ssh/id_rsa.pub | ssh $1@robotino "cat >> /home/$1/.ssh/authorized_keys"
	sudo -u $1 ssh $1@robotino 'exit'
	sudo su -c "rosdep update" $1
	sudo su -c "mkdir -p ~/catkin_ws" $1
    
    echo "done adding user"
else
    echo "No username provided"
fi

